### ISSUE TITLE
Failling to import EP+ 9.1 (with schema updated) examplefile CmplxGlz_MeasuredDeflectionAndShading.idf

### ISSUE THREAD

**Issue by FrancisBases** [SchildCode/EpXL#1]
Hi how are you Professor Peter Schild, Firstly congratulations for your contributions.
Would like your feedback on the following behaviours I found which look like small bugs although I am not sure:
#1 I was trying to run the EpXL simulation on the EP+ 9.1 (with schema updated) C:\EnergyPlusV9-1-0\ExampleFiles\CmplxGlz_MeasuredDeflectionAndShading.idf
-	It Fails to import into the worksheet
-	Q: can you test it and fix the necessary issues ?
Thanks in advance !

**Comment by SchildCode** [comment]
This issue is solved from version v190820.
The file you tried to import contains matrices (Matrix:TwoDimension object) containing 145\*145 elements, which is more than the maximum number of columns in Excel: 16384 columns. This issue was fixed by storing Matrix:TwoDimension objects in semicolon-separated values in row-major order: Thus a 10*20 matrix is stored in 10 spreadsheet cells, with each cell containing a string of 20 semicolon-separated values for a matrix row. Thus EpXL can now hypothetically store matrices of up to maximum 16384 rows * 16384 columns (assuming single digit elements, as spreadsheet cells can store strings of max 32768 characters).

**Comment by FrancisBases** [comment]
Awesome Professor, big respect and greetings for this contribution.

**Comment by FrancisBase** [comment]
BTW, for Win10 64 bit users, Excel 2016, the following instructions or perhaps code, could be considered optionally (https://stackoverflow.com/questions/9725882/getting-scriptcontrol-to-work-with-excel-2010-x64):
Public Sub LoadJSONschema()
...
    'Initialize JSON parser. Do only once
    'Set scriptEngine = CreateObject("MSScriptControl.ScriptControl") 'New ScriptControl (late binding to 'Microsoft Script Control 1.0') no win10 64 compatibility.
    Set scriptEngine = CreateObjectx86("ScriptControl") 'New ScriptControl (late binding to 'Microsoft Script Control 1.0')
...
    'FRANC
    CreateObjectx86 , True ' close mshta host window at the end
    
End Sub

Sub ParseJSON(JSONstr$, IDFr&)
...
    'Initialize JSON parser. Do only once
    'Set scriptEngine = CreateObject("MSScriptControl.ScriptControl") 'New ScriptControl (late binding to 'Microsoft Script Control 1.0')
    Set scriptEngine = CreateObjectx86("ScriptControl") 'New ScriptControl (late binding to 'Microsoft Script Control 1.0')
...
    'FRANC
    CreateObjectx86 , True ' close mshta host window at the end
    
QuitSub:
    Application.EnableEvents = True
    Application.Calculation = xlCalculationAutomatic
    Application.ScreenUpdating = True
    If errMsg <> vbNullString Then
        Application.StatusBar = "Aborted parsing epJSON"
        MsgBox errMsg, vbExclamation + vbMsgBoxSetForeground, "EpXL"
        JSONstr = vbNullString 'clear to avoid parsing
    End If
    DoEvents
End Sub
Function CreateObjectx86(Optional sProgID, Optional bClose = False)

    Static oWnd As Object
    Dim bRunning As Boolean

    #If Win64 Then
        bRunning = InStr(TypeName(oWnd), "HTMLWindow") > 0
        If bClose Then
            If bRunning Then oWnd.Close
            Exit Function
        End If
        If Not bRunning Then
            Set oWnd = CreateWindow()
            oWnd.execScript "Function CreateObjectx86(sProgID): Set CreateObjectx86 = CreateObject(sProgID): End Function", "VBScript"
        End If
        Set CreateObjectx86 = oWnd.CreateObjectx86(sProgID)
    #Else
        Set CreateObjectx86 = CreateObject(sProgID)
    #End If

End Function
Function CreateWindow()

    ' source http://forum.script-coding.com/viewtopic.php?pid=75356#p75356
    Dim sSignature, oShellWnd, oProc

    On Error Resume Next
    sSignature = Left(CreateObject("Scriptlet.TypeLib").GUID, 38)
    CreateObject("WScript.Shell").Run "%systemroot%\syswow64\mshta.exe about:""about:<head><script>moveTo(-32000,-32000);document.title='x86Host'</script><hta:application showintaskbar=no /><object id='shell' classid='clsid:8856F961-340A-11D0-A96B-00C04FD705A2'><param name=RegisterAsBrowser value=1></object><script>shell.putproperty('" & sSignature & "',document.parentWindow);</script></head>""", 0, False
    Do
        For Each oShellWnd In CreateObject("Shell.Application").Windows
            Set CreateWindow = oShellWnd.GetProperty(sSignature)
            If Err.Number = 0 Then Exit Function
            Err.Clear
        Next
    Loop

End Function

**Comment by FrancisBases** [comment]
BTW, for Win10 64 bit users, Excel 2016, the following instructions or perhaps code, could be considered optionally (https://stackoverflow.com/questions/9725882/getting-scriptcontrol-to-work-with-excel-2010-x64):
```
Public Sub LoadJSONschema()
...
    'Initialize JSON parser. Do only once
    'Set scriptEngine = CreateObject("MSScriptControl.ScriptControl") 'New ScriptControl (late binding to 'Microsoft Script Control 1.0') no win10 64 compatibility.
    Set scriptEngine = CreateObjectx86("ScriptControl") 'New ScriptControl (late binding to 'Microsoft Script Control 1.0')
...
    'FRANC
    CreateObjectx86 , True ' close mshta host window at the end
    
End Sub

Sub ParseJSON(JSONstr$, IDFr&)
...
    'Initialize JSON parser. Do only once
    'Set scriptEngine = CreateObject("MSScriptControl.ScriptControl") 'New ScriptControl (late binding to 'Microsoft Script Control 1.0')
    Set scriptEngine = CreateObjectx86("ScriptControl") 'New ScriptControl (late binding to 'Microsoft Script Control 1.0')
...
    'FRANC
    CreateObjectx86 , True ' close mshta host window at the end
    
QuitSub:
    Application.EnableEvents = True
    Application.Calculation = xlCalculationAutomatic
    Application.ScreenUpdating = True
    If errMsg <> vbNullString Then
        Application.StatusBar = "Aborted parsing epJSON"
        MsgBox errMsg, vbExclamation + vbMsgBoxSetForeground, "EpXL"
        JSONstr = vbNullString 'clear to avoid parsing
    End If
    DoEvents
End Sub
Function CreateObjectx86(Optional sProgID, Optional bClose = False)

    Static oWnd As Object
    Dim bRunning As Boolean

    #If Win64 Then
        bRunning = InStr(TypeName(oWnd), "HTMLWindow") > 0
        If bClose Then
            If bRunning Then oWnd.Close
            Exit Function
        End If
        If Not bRunning Then
            Set oWnd = CreateWindow()
            oWnd.execScript "Function CreateObjectx86(sProgID): Set CreateObjectx86 = CreateObject(sProgID): End Function", "VBScript"
        End If
        Set CreateObjectx86 = oWnd.CreateObjectx86(sProgID)
    #Else
        Set CreateObjectx86 = CreateObject(sProgID)
    #End If

End Function
Function CreateWindow()

    ' source http://forum.script-coding.com/viewtopic.php?pid=75356#p75356
    Dim sSignature, oShellWnd, oProc

    On Error Resume Next
    sSignature = Left(CreateObject("Scriptlet.TypeLib").GUID, 38)
    CreateObject("WScript.Shell").Run "%systemroot%\syswow64\mshta.exe about:""about:<head><script>moveTo(-32000,-32000);document.title='x86Host'</script><hta:application showintaskbar=no /><object id='shell' classid='clsid:8856F961-340A-11D0-A96B-00C04FD705A2'><param name=RegisterAsBrowser value=1></object><script>shell.putproperty('" & sSignature & "',document.parentWindow);</script></head>""", 0, False
    Do
        For Each oShellWnd In CreateObject("Shell.Application").Windows
            Set CreateWindow = oShellWnd.GetProperty(sSignature)
            If Err.Number = 0 Then Exit Function
            Err.Clear
        Next
    Loop

End Function

```

**Comment by SchildCode** [comment]
Yepp, the CreateObjectx86 code is now used in EpXL, enabling use of 64bit Excel
