### ISSUE TITLE
eplustbl.csv not found in simulation discrete

### ISSUE THREAD

**Issue by FrancisBases** [SchildCode/EpXL#10]
![image](https://user-images.githubusercontent.com/24868420/67192095-db616200-f3ea-11e9-9db6-dfb0b570893e.png)

running this file: https://ufile.io/fbzkl10u (v9.1)
It is Example_Files\RoomAirflowNetwork.idf

Normal Simulation runs well, when i click in Discrete it returns the error.

In the folder there is eplustbl.htm, eplusout.csv so perhaps it's simply renaming can fix this.

Thank you in advance.
Note that C:\Users\Francisco Costa\Desktop\archetypes_repository\residential is simply the path where i have RoomAirflowNetwork.idf accordingly.

**Comment by FrancisBases** [comment]
It's resolve, only needed to rename eplustbl.csv into eplusout.csv.

**Comment by SchildCode** [comment]
To generate a eplustbl.csv outout file, simply make sure that you have added object « outputcontrol:Table:Style» to the Input-worksheet, and that its format option is set to «Comma» or «CommaAndHTML».

P.S. Files eplustbl.csv and eplusout.csv are both optional output files, but are quite different.: The former contains predefined summary tables, whilst the latter contains time series for parameters that you select to output by adding Output:Variable objects to your input data sheet. Energyplus command line option ’-r’ automatically runs post-processor ReadVarsESO.exe after simulation, which outputs eplusout.csv.

**Comment by FrancisBases** [comment]
Very good information thank you, i guess i skipped this detail. 

Also am using IdealLoads and hence it requires the ExpandObjects = True ie energyplus.exe -x True does EpXL automatically triggers it, or can leave it always on perhaps.
**Update:**
OutputControl:Table:Style |   | CommaAndHTML | JtoKWH
Output:Table:SummaryReports | | AllSummary
now outputs everything well.
With the same model now this error is not showing, ie is not asking for ExpandObjects, so all works.
Cheers
