### ISSUE TITLE
HVACTemplate Processing

### ISSUE THREAD

**Issue by FrancisBases** [SchildCode/EpXL#11]
Currently seems that cannot simulate with HVACTEmplate objects.
Here is documentation on them: [auxiliary programs](https://bigladdersoftware.com/epx/docs/8-0/input-output-reference/page-061.html) and [https://bigladdersoftware.com/epx/docs/8-3/auxiliary-programs/expandobjects.html](https://bigladdersoftware.com/epx/docs/8-3/auxiliary-programs/expandobjects.html)
Suggestion is to to add expandobjects to commandline runs
in CTRL_M subroutine
Instead of
```vba
        cmdline = exePath & " -w """ & epwPath & """ -d """ & idfDir & """ -r """ & idfNam & """ "
        wsh.Run cmdline, 1, True 'command, windowStyle=1, waitOnReturn=TRUE
```
Can use
```vba
        cmdline = exePath & " -w """ & epwPath & """ -d """ & idfDir & """ -r -x """ & idfNam & """ "
        wsh.Run cmdline, 1, True 'command, windowStyle=1, waitOnReturn=TRUE
```
Otherwise the HVACTemplates' idf files cannot be simulated in epxl it seems.
here is an energyplus idf example: [e.zip](https://github.com/SchildCode/EpXL/files/3800419/e.zip)

After this it looks like only IDF parser works, and epJSON does not because it returns a different result all together.

cheers

**Comment by SchildCode** [comment]
Implemented in EpXL v191112.
