### ISSUE TITLE
EpXL_v190927 - Error when updating schema to EnergyPlus v9.2.0

### ISSUE THREAD

**Issue by jmwoolley** [SchildCode/EpXL#12]
When updating EpXL_v190927 schema to EnergyPlus v9.2.0, I receive the following error:

   Microsoft Visual Basic:
   Run-time error '13':
   Type mismatch

Debug flags EpXL / LoadJSONschema / line 451
  Set key4 = scriptEngine.Run("getProperty", key3, ".*")

**Comment by SchildCode** [comment]
Can be fixed simply by replacing the offending line 451:
-  Set key4 = scriptEngine.Run("getProperty", key3, ".\*")

with these two lines:
-  keys3 = JSONgetKeys(key3)
-  Set key4 = scriptEngine.Run("getProperty", key3, keys3(1))

**This fix is in the next release.**
The reason for this fix is that key3 had only one possible value (".\*") in E+ version 9.1 and earlier, but version 9.2 has two alternative values for key3 (either ".\*" or "^.*\\\S.\*$").

**Comment by jmwoolley** [comment]
This worked. Thank you!
