### ISSUE TITLE
Decimals return error in Epjson

### ISSUE THREAD

**Issue by FrancisBases** [SchildCode/EpXL#4]
Good work with the issues fixing and now it's possible to run matrix twodimn models.
Reproducing:
i) Open EpXL and ctrl+i then browse to C:\EnergyPlusV9-1-0\ExampleFiles\CmplxGlz_MeasuredDeflectionAndShading.idf
ii) It now loads well after ~20min the IDF into Excel.
iii) Try to simulate with option output JSON.
iv) returns error
```
Program Version,EnergyPlus, Version 9.1.0-08d2e308bb, YMD=2019.08.20 20:19,
   ** Severe  ** [json.exception.parse_error.101] parse error at line 624, column 28: syntax error while parsing value - invalid number; expected digit after '.'; last read: '1.<U+000D>'
   **  Fatal  ** Errors occurred on processing input file. Preceding condition(s) cause termination.
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=1
   ..... Last severe error=[json.exception.parse_error.101] parse error at line 624, column 28: syntax error while parsing value - invalid number; expected digit after '.'; last read: '1.<U+000D>'
   ************* Warning:  Node connection errors not checked - most system input has not been read (see previous warning).
   ************* Fatal error -- final processing.  Program exited before simulations began.  See previous error messages.
   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Terminated--Fatal Error Detected. 0 Warning; 1 Severe Errors; Elapsed Time=00hr 00min  0.37sec
```
v) Checking the exported epjson in the offending line 624, it's not parsing well the decimals (and the curly brackets are not sequenced well).
<a href="https://ibb.co/5BXBn3B"><img src="https://i.ibb.co/SRDRdgR/decimal-parse.png" alt="decimal-parse" border="0"></a>
vi) Checking the Object in the EpXL GUI it is also the decimal truncated, and they are not parsed in different cells.
<a href="https://ibb.co/n0F2kWB"><img src="https://i.ibb.co/z5zcfkF/ii-still-not-importing.png" alt="ii-still-not-importing" border="0"></a>
vii) Exporting to IDF and comparing with the original IDF file it leads to the same conclusion.
<a href="https://ibb.co/8D2nz3y"><img src="https://i.ibb.co/992mwXx/decimals.png" alt="decimals" border="0"></a>
Conclusion:
If Output = 0 it may work because IDF is more forgiving with decimals, but in epjson and in excel the parse is not running.
If this is important recommending to fix ok.
Best regards.v

**Comment by SchildCode** [comment]
This issue should be solved from version v190822.
