### ISSUE TITLE
full cycle import / export / import without losses IDF and epJSON

### ISSUE THREAD

**Issue by FrancisBases** [SchildCode/EpXL#7]
It is working for epJSON, for it to work for IDF simply add an empty line programatically and two spaces in the beginning.

It is very simple, the hard work was done already by Prof. Schild so with this is only to enable roundtrip of IDF:

```
    'First line should be empty
    objTF.WriteLine
...
    'Add two spaces
    'objTF.WriteLine JSONstr & ";"
    objTF.WriteLine "  " & JSONstr & ";"
```

Full sub here:
```
Sub SaveIDF(IDFpath$)
    'Build legacy format .IDF file string. Will be depreciated when EnergyPlus v10 is released
    Dim t0# 'start time
    Dim IDFr& 'IDF row
    Dim IDDr& 'IDD row
    Dim cc& 'column (applies to both idf and IDD simultaneously)
    Dim IDFc As Range 'IDF cell
    Dim IDFs$
    Dim JSONstr$
    Dim MatrixCi& 'Matrix input column counter (row-major order)
    Dim objFSO As Object
    'Dim objTF As Object

    Call CTRL_Q 'vet input data, and count OTrows
    If errMsg <> vbNullString Then Exit Sub
    
    t0 = Timer
    Set IDFc = Worksheets("Input").Range("A1")
    Set objFSO = CreateObject("Scripting.FileSystemObject")
    Set objTF = objFSO.CreateTextFile(IDFpath)
    
    'First line should be empty
    objTF.WriteLine
    
    '1) Generate IDF string
    For IDFr = 1 To OTrows
        IDDr = OTlist(IDFr)
        If IDDr > 0 Then 'data in this row
            Application.StatusBar = "Building IDF " & IDFr * 100 \ OTrows & "%"
            JSONstr = vbNullString
            DoEvents
            For cc = 1 To OTlast(IDFr)
                IDFs = oStr(IDFc(IDFr, cc))
                Select Case cc
                Case 1 '1. object type
                    JSONstr = IDFs
                    MatrixCi = 0
                    If IDFs = "Matrix:TwoDimension" Then MatrixCi = 1 'special case
                Case 2 '2.name column
                    If O_Tname(IDDr, 4) <> vbNullString Then JSONstr = JSONstr & "," & IDFs 'name column exists
                Case Else '3. fixed+extended fields
                    If MatrixCi = 1 Then
                        objTF.WriteLine JSONstr & ","
                        JSONstr = Replace(IDFs, ";", ",") 'special case: matrix row with semicolon-separated values
                    Else
                        JSONstr = JSONstr & "," & IDFs
                    End If
                End Select
            Next
            'Add two spaces
            'objTF.WriteLine JSONstr & ";"
            objTF.WriteLine "  " & JSONstr & ";"
        End If
    Next
    objTF.WriteLine "!This file was generated by program EpXL (https://github.com/SchildCode/EpXL)"
    objTF.WriteLine "!Weather file: " & Worksheets("Simulate").Range("B2")

    objTF.Close
    Set objTF = Nothing
    Set objTF = Nothing
    Application.StatusBar = "Saved " & IDFpath
    Debug.Print "SaveIDF took " & CLng(Timer - t0) & " seconds."
End Sub
```

**Comment by FrancisBases** [comment]
Furthermore, after this fix, doing a robustness test with the larger file from Example Files **CmplxGlz_MeasuredDeflectionAndShading.idf**:

i) Import IDF (success)
ii) Export IDF (success)
iii)  Import the exported IDF results:

![image](https://user-images.githubusercontent.com/24868420/65560368-4166e080-df36-11e9-953e-5acbfc444621.png)

Should be this:

![image](https://user-images.githubusercontent.com/24868420/65560509-e4b7f580-df36-11e9-94fb-59589e4a1ca8.png)
Looks like saveIDF is bypassing Matrix:TwoDimension objects.

Now doing the "robustness" test with epjson
i) Import IDF (success)
ii) Export epJSON (success)
iii) Import the exported epJSON Holds around 29,41%
Usually it can be due to the TwoDim and possible for loops, using dictionary objects is usually a lot faster if you can use keys for mapping objects accordingly.

Cheers.

**Comment by SchildCode** [comment]
This was solved by fixing two bugs: 
- "p1 = 1" was changed to "p1 = -1" in Sub ParseIDF
- "lastcol = Fxt0 + OextensibleSize" was commented out in Sub CTRL_Q

**Comment by FrancisBase** [comment]
Cheers and it works.

**Comment by FrancisBases** [comment]
Cheers!

**Comment by FrancisBases** [comment]
After testing it looks like that when doing step ii) Exporting as IDF it is working well except it is not reconverting excel decimals ('.') back into IDF decimals ('.').

![image](https://user-images.githubusercontent.com/24868420/65709670-49836500-e089-11e9-9881-8dd94ef10c49.png)

Here is copy.idf a subset for reproduce of CmplxGlz_MeasuredDeflectionAndShading.idf
https://drive.google.com/file/d/1NnADJgAVzK--277nchesAwjYxK9ILlDc/view?usp=sharing cheers.

**Comment by SchildCode** [comment]
Fixed in v190927
