### ISSUE TITLE
epjson

### ISSUE THREAD

**Issue by FrancisBases** [SchildCode/EpXL#8]
Congratulations for this very good work because it is improving very well. 

After testing found out some decimals in twodims are not converted from excel ',' into IDF '.' so check the other conversation about it if possible and thanks in advance.

Here wanted to contribute with some ideas, namely improve for epjson because it really is slow when working with matrices.

By simply testing this with the example provided in previous it becomes clear.

One idea would be to use dictionaries. VBA does not have an internal implementation of a dictionary, but from VBA you can still use the dictionary object from MS Scripting Runtime Library.

Again, dictionaries in VBA are much less powerful than python, having lots of limitations in VBA although a dictionary of dictionaries can be tested to see if it improves here.

Note: if you think this is not important at least for now, i totally agree with closing or taking this out as non issue. 

Cheers.

**Comment by SchildCode** [comment]
Fixed in Version v190927.

Regarding the issue of data dictionaries: I agree that is a very good way of storing and manipulating the data in memory akin to JSON, but it would not change the way EpXL stores the data in tabular form in the worksheet. I suggest that you try it out yourself and give feedback.

**Comment by FrancisBases** [comment]
Yes i agree, i have tested them a bit, and i think currently EpXL have already robustness, of course, improve is always possible but it's not a priority i totally think also.

Usually user experience is a little hindered for processes that take more than one minute and Excel freezes, even if they are successful. In these cases i normally implement a progress bar which is easy to do as you know. 

I'm going to test this and if necessary will feedback of course.

Again i take the opportunity to give congratulations for this solution, Cheers.

**Comment by SchildCode** [comment]
P.S. All import/export processes in EpXL show progress in the Excel window status bar. I recently modified the progress info for epJSON import, to show more detail.
